language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t herederpharao/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true herederpharao/react-test npm run test

after_success:
    - docker build -t herederpharao/multi-client ./client
    - docker build -t herederpharao/multi-nginx ./nginx
    - docker build -t herederpharao/multi-server ./server
    - docker build -t herederpharao/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push herederpharao/multi-client
    - docker push herederpharao/multi-nginx
    - docker push herederpharao/multi-server
    - docker push herederpharao/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-central-1-727700104260
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY